#!/usr/bin/env python3
import sys

def to_bin(hex: str) -> str:
    dec = int(hex, 16)
    spec = '{fill}{align}{width}{type}'.format(fill='0', align='>', width=8, type='b')
    return format(dec, spec)

def to_hex(bin: str) -> str:
    dec = int(bin, 2)
    spec = '{:02X}'
    return ''.join(spec.format(dec))

if len(sys.argv) == 2:
    num = sys.argv[1]
    if len(num) == 2:
        num = to_bin(num)
    elif len(num) == 8:
        num = to_hex(num)
    print(num)
else:
    print("Wrong arguments, hex_to_bin {hex|bin}")


